blank_issues_enabled: false
contact_links:
  - name: General discussion
    url: https://github.com/mudabs/Ecommerce-Frontend/discussions
    about: Use Discussions for open-ended ideas and questions.
